<?php
require __DIR__.'/../vendor/autoload.php';require __DIR__.'/../app/Support.php';require __DIR__.'/../app/Database.php';require __DIR__.'/../app/Security.php';require __DIR__.'/../app/Auth.php';require __DIR__.'/../app/Cpanel.php';require __DIR__.'/../app/Mailer.php';require __DIR__.'/../app/Mailbox.php';require __DIR__.'/../app/OAuth.php';
$app=require __DIR__.'/../config/app.php';session_name($app['session']);session_start();$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH);$base=rtrim(parse_url($app['url'],PHP_URL_PATH)?:'/mail','/');$path=str_starts_with($path,$base)?substr($path,strlen($base)):$path;$path=$path?:'/';
if($path==='/logout'){Auth::logout();redirect('/login.php');}
if($path==='/api/inbox'){$u=Auth::require();try{json_response(['messages'=>(new Mailbox())->messages($u['email'],Security::decrypt($u['mailbox_password_enc']))]);}catch(Throwable $e){json_response(['error'=>'Mailbox connection failed'],502);}}
if($path==='/api/send'&&$_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$u=Auth::require();$to=trim($_POST['to']??'');$subject=trim($_POST['subject']??'');$body=(string)($_POST['body']??'');if(!filter_var($to,FILTER_VALIDATE_EMAIL)||$subject==='')json_response(['error'=>'Invalid message'],422);try{(new Mailer())->send($u['email'],Security::decrypt($u['mailbox_password_enc']),$to,$subject,$body);json_response(['ok'=>true]);}catch(Throwable $e){json_response(['error'=>'Unable to send message'],502);}}
if($path==='/api/oauth/userinfo'){$token=preg_replace('/^Bearer\s+/i','',$_SERVER['HTTP_AUTHORIZATION']??'');$u=(new OAuth())->userFromBearer($token);if(!$u)json_response(['error'=>'invalid_token'],401);json_response(['sub'=>(string)$u['id'],'email'=>$u['email'],'name'=>$u['display_name']?:$u['username'],'preferred_username'=>$u['username']]);}
if($path==='/oauth/authorize'){$u=Auth::require();$client=$_GET['client_id']??'';$redirect=$_GET['redirect_uri']??'';$scope=$_GET['scope']??'openid profile email';$state=$_GET['state']??'';if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();try{redirect((new OAuth())->authorize($u,$_POST['client_id']??$client,$_POST['redirect_uri']??$redirect,$_POST['scope']??$scope,$_POST['state']??$state));}catch(Throwable $e){$error=$e->getMessage();}}require __DIR__.'/../views/oauth-consent.php';exit;}
if($path==='/oauth/token'&&$_SERVER['REQUEST_METHOD']==='POST'){try{json_response((new OAuth())->token($_POST));}catch(Throwable $e){json_response(['error'=>'invalid_grant','error_description'=>$e->getMessage()],400);}}
if($path==='/dev.php'){$u=Auth::require();if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$name=trim($_POST['name']??'');$redirects=trim($_POST['redirect_uris']??'');if($name&&$redirects){$id=random_token(18);$secret=random_token(32);$s=Database::pdo()->prepare('INSERT INTO bm_oauth_clients(user_id,client_id,client_secret_hash,name,redirect_uris) VALUES(?,?,?,?,?)');$s->execute([$u['id'],$id,password_hash($secret,PASSWORD_DEFAULT),$name,$redirects]);$newClient=['client_id'=>$id,'client_secret'=>$secret,'name'=>$name];}}$s=Database::pdo()->prepare('SELECT * FROM bm_oauth_clients WHERE user_id=? ORDER BY id DESC');$s->execute([$u['id']]);$clients=$s->fetchAll();require __DIR__.'/../views/dev.php';exit;}
if($path==='/register.php'){if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$username=strtolower(trim($_POST['username']??''));$email=$username.'@'.config('domain');$password=(string)($_POST['password']??'');$display=trim($_POST['display_name']??$username);if(!preg_match('/^[a-z0-9][a-z0-9._-]{2,31}$/',$username)||strlen($password)<10){$error='Invalid username or password.';}else{try{(new Cpanel())->create($username,$password,1024);$p=Database::pdo();$s=$p->prepare('INSERT INTO bm_users(email,username,password_hash,mailbox_password_enc,display_name) VALUES(?,?,?,?,?)');$s->execute([$email,$username,password_hash($password,PASSWORD_DEFAULT),Security::encrypt($password),$display]);Auth::login(['id'=>$p->lastInsertId()]);redirect('/');}catch(Throwable $e){$error='Could not create mailbox. Check cPanel email API configuration.';}}}require __DIR__.'/../views/register.php';exit;}
if($path==='/login.php'){if(Auth::user())redirect('/');if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$email=strtolower(trim($_POST['email']??''));$password=(string)($_POST['password']??'');$s=Database::pdo()->prepare('SELECT * FROM bm_users WHERE email=? AND active=1');$s->execute([$email]);$u=$s->fetch();if($u&&password_verify($password,$u['password_hash'])){Auth::login($u);redirect('/');}$error='ایمیل یا رمز عبور اشتباه است.';}require __DIR__.'/../views/login.php';exit;}
$u=Auth::require();require __DIR__.'/../views/dashboard.php';
